# Configuration file for KnockbackFFA
# KnockbackFFA by @ByBezge

#If you need help, look at the ReadMe.md or how_to_use.txt


#Every change needs an Server Restart!


#Language of the Plugin: only supportet eng/deu
language: deu


#GamePrefix
Prefix: §7[§6KnockbackFFA§7]

#KnockbackFFA Arena's:

#Example:
#Arenas:
#- Test
#- Test2

Arenas: [KnockbackFFA-1]

#Activate/Deactivate Title (true/false)
Title: true

#Maximum of Players per Arena
MaxPlayer: 25

#ProtectionRadius where PvP is disabled
ProtectionRadius: 10

#Sign
#Line1: KnockbackFFA
#Line2: Your Arena world
